config/routes.rb
Rails.application.routes.draw do
  resources :events
  # get 'events/:id/add_attendee', to: 'attendees#new', as: 'attendee'
  # post 'events/:id/add_attendee', to: 'attendees#create'
  resources :attendees, except: [:index, :show]

  get 'pages/home'
  devise_for :users, path: '', path_names: {sign_up: 'register', sign_in: 'login', sign_out: 'logout'},
  controllers: {
        sessions: 'users/sessions'
      }
  root to: 'pages#home'
end

app/models/attendee.rb
class Attendee < ApplicationRecord
    has_many :tickets
    has_many :events, through: :tickets
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: %i[ show edit update destroy ]
  before_action :set_event, only: [:new, :create]
  before_action :require_current_user, only: [:new, :create]

  # GET /attendees or /attendees.json
  # def index
  #   @attendees = Attendee.all
  # end

  # GET /attendees/1 or /attendees/1.json
  # def show
  # end

  # GET /attendees/new
  def new
    @attendee = Attendee.new()
  end

  # GET /attendees/1/edit
  def edit
  end

  # POST /attendees or /attendees.json
  def create
    if Attendee.find_by name: attendee_params[:name]
      @attendee = Attendee.find_by name: attendee_params[:name]
    else
      @attendee = Attendee.new(attendee_params)
    end
    
    @attendee.events << @event

    respond_to do |format|
      if @attendee.save
        format.html { redirect_to @event, notice: "Attendee was successfully created." }
        # format.json { render :show, status: :created, location: @attendee }
      else
        format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PATCH/PUT /attendees/1 or /attendees/1.json
  def update
    respond_to do |format|
      if @attendee.update(attendee_params)
        format.html { redirect_to @attendee, notice: "Attendee was successfully updated." }
        format.json { render :show, status: :ok, location: @attendee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1 or /attendees/1.json
  def destroy
    @attendee.destroy
    respond_to do |format|
      format.html { redirect_to attendees_url, notice: "Attendee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attendee_params
      params.require(:attendee).permit(:name, :phone_number, :email, event_ids: [])
    end
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/attendees/_form.html.erb
<%= form_with(model: attendee, event_id: 'petr') do |form| %>
  <% if attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
        <% attendee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <%= hidden_field_tag(:event_id, @event.id) %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attendees/edit.html.erb
<h1>Editing Attendee</h1>

<%= render 'form', attendee: @attendee %>

<%= link_to 'Show', @attendee %> |
<%= link_to 'Back', attendees_path %>

app/views/attendees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendees.each do |attendee| %>
      <tr>
        <td><%= attendee.name %></td>
        <td><%= attendee.phone_number %></td>
        <td><%= attendee.email %></td>
        <td><%= link_to 'Show', attendee %></td>
        <td><%= link_to 'Edit', edit_attendee_path(attendee) %></td>
        <td><%= link_to 'Destroy', attendee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendee', new_attendee_path %>

app/views/attendees/new.html.erb
<h1>New Attendee</h1>
for <%= @event.name %>

<%= render 'form', attendee: @attendee %>

<%# <%= link_to 'Back', attendees_path %>

app/views/attendees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @attendee.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @attendee.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @attendee.email %>
</p>

<%= link_to 'Edit', edit_attendee_path(@attendee) %> |
<%= link_to 'Back', attendees_path %>